"""Фикс модели Team

Revision ID: 036c5e0e5dce
Revises: 50d526de20d9
Create Date: 2026-05-20 11:23:07.233208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '036c5e0e5dce'
down_revision: Union[str, Sequence[str], None] = '50d526de20d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('manager_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'teams', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'manager_id')
    # ### end Alembic commands ###
