"""Описание Team nullable

Revision ID: 1d10af346970
Revises: 036c5e0e5dce
Create Date: 2026-05-21 08:03:05.958418

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1d10af346970"
down_revision: Union[str, Sequence[str], None] = "036c5e0e5dce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "teams", "description", existing_type=sa.VARCHAR(length=500), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "teams", "description", existing_type=sa.VARCHAR(length=500), nullable=False
    )
    # ### end Alembic commands ###
