"""Уникальный индекс на User email, Team name

Revision ID: 34d764a60043
Revises: b42b1cf97f36
Create Date: 2026-05-18 16:17:55.969171

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "34d764a60043"
down_revision: Union[str, Sequence[str], None] = "b42b1cf97f36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "teams", ["name"])
    op.create_unique_constraint(None, "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_email_key", "users", type_="unique")
    op.drop_constraint("teams_name_key", "teams", type_="unique")
    # ### end Alembic commands ###
