"""Фиксы моделей

Revision ID: 493722deebda
Revises: 1cfe04fa3a91
Create Date: 2026-05-16 23:08:04.995113

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "493722deebda"
down_revision: Union[str, Sequence[str], None] = "1cfe04fa3a91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("task", "meeting", name="eventtype").create(op.get_bind())
    op.drop_constraint(op.f("employees_schedule_id_key"), "employees", type_="unique")
    op.drop_constraint(
        op.f("employees_schedule_id_fkey"), "employees", type_="foreignkey"
    )
    op.drop_column("employees", "schedule_id")
    op.add_column(
        "events",
        sa.Column("type", sa.Enum("task", "meeting", name="eventtype"), nullable=False),
    )
    op.alter_column(
        "events",
        "start_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "events",
        "end_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.add_column("schedules", sa.Column("employee_id", sa.Integer(), nullable=False))
    op.alter_column(
        "schedules",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.create_unique_constraint(None, "schedules", ["employee_id"])
    op.create_foreign_key(None, "schedules", "employees", ["employee_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "schedules", type_="foreignkey")
    op.drop_constraint(None, "schedules", type_="unique")
    op.alter_column(
        "schedules",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.drop_column("schedules", "employee_id")
    op.alter_column(
        "events",
        "end_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "events",
        "start_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    sa.Enum(name="eventtype").drop(op.get_bind())
    op.drop_column("events", "type")
    op.add_column(
        "employees",
        sa.Column("schedule_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("employees_schedule_id_fkey"),
        "employees",
        "schedules",
        ["schedule_id"],
        ["id"],
    )
    op.create_unique_constraint(
        op.f("employees_schedule_id_key"),
        "employees",
        ["schedule_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
