"""time_zone перешел к графику

Revision ID: 50d526de20d9
Revises: 34d764a60043
Create Date: 2026-05-19 18:10:31.940645

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "50d526de20d9"
down_revision: Union[str, Sequence[str], None] = "34d764a60043"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "time_zone")
    op.add_column("schedules", sa.Column("time_zone", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedules", "time_zone")
    op.add_column(
        "employees",
        sa.Column("time_zone", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
