"""Отчетство nullable

Revision ID: 667140e2f5c6
Revises: c4115155b3ca
Create Date: 2026-05-23 19:54:07.861637

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "667140e2f5c6"
down_revision: Union[str, Sequence[str], None] = "c4115155b3ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "employees", "patronymic", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "employees", "patronymic", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###
