"""Добавлены поля для safe delete

Revision ID: b42b1cf97f36
Revises: 493722deebda
Create Date: 2026-05-17 20:27:42.316098

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b42b1cf97f36"
down_revision: Union[str, Sequence[str], None] = "493722deebda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employee_events", "id")
    op.create_primary_key(
        "pk_employee_events",  # имя constraint
        "employee_events",  # таблица
        ["employee_id", "event_id"],  # колонки
    )
    op.add_column("employees", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column("events", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column(
        "schedule_exceptions", sa.Column("is_active", sa.Boolean(), nullable=False)
    )
    op.add_column("schedules", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column("teams", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("pk_employee_events", "employee_events", type_="primary")
    op.add_column(
        "employee_events",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.drop_column("users", "is_active")
    op.drop_column("teams", "is_active")
    op.drop_column("schedules", "is_active")
    op.drop_column("schedule_exceptions", "is_active")
    op.drop_column("events", "is_active")
    op.drop_column("employees", "is_active")
    op.add_column(
        "employee_events",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    # ### end Alembic commands ###
