"""Отчество дни работы и должность

Revision ID: c4115155b3ca
Revises: 1d10af346970
Create Date: 2026-05-22 01:37:58.660929

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c4115155b3ca"
down_revision: Union[str, Sequence[str], None] = "1d10af346970"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employees", sa.Column("patronymic", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "employees", sa.Column("position", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "schedules",
        sa.Column("work_days", postgresql.ARRAY(sa.Integer()), nullable=False),
    )
    op.drop_column("schedules", "shift_work_days")
    op.drop_column("schedules", "shift_start_date")
    op.drop_column("schedules", "shift_rest_days")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedules",
        sa.Column("shift_rest_days", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "schedules",
        sa.Column("shift_start_date", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "schedules",
        sa.Column("shift_work_days", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("schedules", "work_days")
    op.drop_column("employees", "position")
    op.drop_column("employees", "patronymic")
    # ### end Alembic commands ###
