"""Личные данные nullable

Revision ID: e60aae0ded6a
Revises: 667140e2f5c6
Create Date: 2026-05-25 02:42:53.946344

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e60aae0ded6a"
down_revision: Union[str, Sequence[str], None] = "667140e2f5c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("employees", "team_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("employees", "team_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
